export const dashboardData = {
    greeting: {
        timeOfDay: 'Good evening',
        alerts: 1,
        updates: 2,
    },
    weather: {
        location: 'Sidi Bel Abbes',
        temp: 24,
        condition: 'Partly Cloudy',
        high: 28,
        low: 15,
        humidity: 42,
    },
    inboxes: [
        {
            name: '@fortera.co',
            icon: 'briefcase',
            iconColor: 'text-primary',
            unread: 12,
            bg: 'rgba(239,68,68,.15)',
            color: '#f87171',
            border: 'rgba(239,68,68,.25)',
        },
        {
            name: '@example.com',
            icon: 'code-2',
            iconColor: 'text-chart-3',
            unread: 4,
            bg: 'rgba(245,158,11,.15)',
            color: '#fbbf24',
            border: 'rgba(245,158,11,.25)',
        },
        {
            name: 'Gmail',
            icon: 'mail',
            iconColor: 'text-destructive',
            unread: 0,
            bg: 'rgba(255,255,255,.06)',
            color: '#64748b',
            border: 'rgba(255,255,255,.08)',
        },
    ],
    network: {
        down: '854 Mbps',
        downPercent: 85,
        up: '92 Mbps',
        upPercent: 45,
        ping: '12ms',
        isp: '1 Gbps',
    },
    pihole: {
        queries: '82.3k',
        blockedPercent: 16,
        blockedToday: '~13.2k',
    },
    githubStats: {
        stars: '1.2k',
        prs: 8,
        issues: 14,
        downloads: '45k',
    },
    services: [
        {
            id: 'media',
            name: 'media-arr',
            badge: 'Media Stack',
            theme: {
                base: 'rgba(168,85,247)',
                icon: 'film',
                color: 'text-chart-1',
            },
            status: { type: 'warn', text: '1 update' },
            containersCount: 7,
            linkText: 'Media details',
            items: [
                {
                    name: 'Jellyfin',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/jellyfin.png',
                    status: 'Running'
                },
                {
                    name: 'Seerr',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/seerr.png',
                    status: 'Running'
                },
                {
                    name: 'Radarr',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radarr.png',
                    status: 'Running'
                },
                {
                    name: 'Sonarr',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/sonarr.png',
                    status: 'Update!'
                },
                {
                    name: 'Transmission',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/transmission.png',
                    status: 'Running'
                },
                {
                    name: 'Prowlarr',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/prowlarr.png',
                    status: 'Running'
                },
                {
                    name: 'Bazaarr',
                    icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/bazarr.png',
                    status: 'Running'
                }
            ],
        },
    ],
    repos: [
        {
            name: 'laravel-filament-app',
            version: 'v2.3.0',
            versionBg: 'rgba(34,197,94,.1)',
            versionColor: '#4ade80',
            versionBorder: 'rgba(34,197,94,.2)',
            desc: 'Filament admin panel integration for Laravel.',
            stars: 842,
            forks: 124,
            issues: 7,
            prs: 3,
        },
        {
            name: 'fortera-sdk',
            version: 'v1.0.8',
            versionBg: 'rgba(99,102,241,.1)',
            versionColor: '#a5b4fc',
            versionBorder: 'rgba(99,102,241,.2)',
            desc: 'Official PHP SDK for the Fortera API.',
            stars: 215,
            forks: 31,
            issues: 5,
            prs: 2,
        },
        {
            name: 'docker-homelab-kit',
            version: 'v0.9.2',
            versionBg: 'rgba(245,158,11,.1)',
            versionColor: '#fcd34d',
            versionBorder: 'rgba(245,158,11,.2)',
            desc: 'Docker compose stacks for homelabbers.',
            stars: 198,
            forks: 47,
            issues: 2,
            prs: 3,
        },
    ],
    servers: [
        {
            name: 'El-Baph',
            type: 'Home',
            ip: '192.168.1.10',
            status: 'Clear',
            statusType: 'ok',
            cpu: 20,
            ram: 45,
            disk: 65,
            cpuColor: 'bg-chart-3',
            ramColor: 'bg-primary',
            diskColor: 'bg-chart-1',
        },
        {
            name: 'Fortera-Prod',
            type: 'Prod',
            ip: '104.21.5.12',
            status: 'BOT',
            statusType: 'crit',
            alert: 'Netdata: CPU >98% 2hrs · bot crawl · ISP notified',
            cpu: 98,
            ram: 82,
            disk: 50,
            cpuColor: 'bg-destructive',
            ramColor: 'bg-chart-4',
            diskColor: 'bg-chart-1',
        },
        {
            name: 'Client-VPS-01',
            type: 'Client',
            ip: '172.64.3.1',
            status: 'OK',
            statusType: 'ok',
            cpu: 5,
            ram: 15,
            disk: 30,
            cpuColor: 'bg-chart-3',
            ramColor: 'bg-primary',
            diskColor: 'bg-chart-1',
        },
    ],
    pullRequests: [
        {
            title: 'feat: bulk export',
            icon: 'git-pull-request',
            iconColor: 'text-chart-3',
            time: '2h',
        },
        {
            title: 'Pagination broken',
            icon: 'circle-dot',
            iconColor: 'text-destructive',
            time: '5h',
        },
        {
            title: 'fix: auth token expiry',
            icon: 'git-pull-request',
            iconColor: 'text-chart-3',
            time: '1d',
        },
        {
            title: 'SDK: null pointer v1.0.8',
            icon: 'circle-dot',
            iconColor: 'text-destructive',
            time: '2d',
        },
        {
            title: 'feat: webhook support',
            icon: 'git-pull-request',
            iconColor: 'text-chart-3',
            time: '3d',
        },
    ],
    containers: {
        total: 24,
        running: 23,
        update: 1,
        list: [
            {
                name: 'redis',
                status: 'Up 10d · healthy',
                dotColor: 'bg-chart-3',
                statusColor: 'text-muted-foreground',
            },
            {
                name: 'postgres',
                status: 'Up 10d · healthy',
                dotColor: 'bg-chart-3',
                statusColor: 'text-muted-foreground',
            },
            {
                name: 'Outline',
                status: 'Up 10d',
                dotColor: 'bg-chart-3',
                statusColor: 'text-muted-foreground',
            },
            {
                name: 'Jellyfin',
                status: 'Up 7d',
                dotColor: 'bg-chart-3',
                statusColor: 'text-muted-foreground',
            },
            {
                name: 'Sonarr',
                status: 'Update avail.',
                dotColor: 'bg-chart-4',
                statusColor: 'text-chart-4',
            },
            {
                name: 'Pi-hole',
                status: 'Up 22d',
                dotColor: 'bg-chart-3',
                statusColor: 'text-muted-foreground',
            },
        ],
    },
};
